// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ppos_storage.proto

/*
Package ppos_storage is a generated protocol buffer package.

It is generated from these files:
	ppos_storage.proto

It has these top-level messages:
	CandidateInfo
	Refund
	RefundArr
	CandidateTemp
	TxHashArr
	Field
	TicketDependency
	TicketTemp
	PB_PPosTemp
*/
package ppos_storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CandidateInfo struct {
	Deposit     string `protobuf:"bytes,1,opt,name=Deposit" json:"Deposit,omitempty"`
	BlockNumber string `protobuf:"bytes,2,opt,name=BlockNumber" json:"BlockNumber,omitempty"`
	TxIndex     uint32 `protobuf:"varint,3,opt,name=TxIndex" json:"TxIndex,omitempty"`
	CandidateId []byte `protobuf:"bytes,4,opt,name=CandidateId,proto3" json:"CandidateId,omitempty"`
	Host        string `protobuf:"bytes,5,opt,name=Host" json:"Host,omitempty"`
	Port        string `protobuf:"bytes,6,opt,name=Port" json:"Port,omitempty"`
	Owner       []byte `protobuf:"bytes,7,opt,name=Owner,proto3" json:"Owner,omitempty"`
	//  string    From          = 8;
	Extra  string `protobuf:"bytes,8,opt,name=Extra" json:"Extra,omitempty"`
	Fee    uint32 `protobuf:"varint,9,opt,name=Fee" json:"Fee,omitempty"`
	TxHash []byte `protobuf:"bytes,10,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	TOwner []byte `protobuf:"bytes,11,opt,name=TOwner,proto3" json:"TOwner,omitempty"`
}

func (m *CandidateInfo) Reset()                    { *m = CandidateInfo{} }
func (m *CandidateInfo) String() string            { return proto.CompactTextString(m) }
func (*CandidateInfo) ProtoMessage()               {}
func (*CandidateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CandidateInfo) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *CandidateInfo) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *CandidateInfo) GetTxIndex() uint32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *CandidateInfo) GetCandidateId() []byte {
	if m != nil {
		return m.CandidateId
	}
	return nil
}

func (m *CandidateInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CandidateInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CandidateInfo) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CandidateInfo) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *CandidateInfo) GetFee() uint32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *CandidateInfo) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *CandidateInfo) GetTOwner() []byte {
	if m != nil {
		return m.TOwner
	}
	return nil
}

type Refund struct {
	Deposit     string `protobuf:"bytes,1,opt,name=Deposit" json:"Deposit,omitempty"`
	BlockNumber string `protobuf:"bytes,2,opt,name=BlockNumber" json:"BlockNumber,omitempty"`
	Owner       []byte `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
}

func (m *Refund) Reset()                    { *m = Refund{} }
func (m *Refund) String() string            { return proto.CompactTextString(m) }
func (*Refund) ProtoMessage()               {}
func (*Refund) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Refund) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *Refund) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Refund) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

type RefundArr struct {
	Defeats []*Refund `protobuf:"bytes,1,rep,name=Defeats" json:"Defeats,omitempty"`
}

func (m *RefundArr) Reset()                    { *m = RefundArr{} }
func (m *RefundArr) String() string            { return proto.CompactTextString(m) }
func (*RefundArr) ProtoMessage()               {}
func (*RefundArr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RefundArr) GetDefeats() []*Refund {
	if m != nil {
		return m.Defeats
	}
	return nil
}

type CandidateTemp struct {
	//  three round witness
	Pres  []*CandidateInfo `protobuf:"bytes,1,rep,name=pres" json:"pres,omitempty"`
	Currs []*CandidateInfo `protobuf:"bytes,2,rep,name=currs" json:"currs,omitempty"`
	Nexts []*CandidateInfo `protobuf:"bytes,3,rep,name=nexts" json:"nexts,omitempty"`
	// can pool
	Imms []*CandidateInfo `protobuf:"bytes,4,rep,name=imms" json:"imms,omitempty"`
	Res  []*CandidateInfo `protobuf:"bytes,5,rep,name=res" json:"res,omitempty"`
	// refunds
	Refunds map[string]*RefundArr `protobuf:"bytes,6,rep,name=refunds" json:"refunds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CandidateTemp) Reset()                    { *m = CandidateTemp{} }
func (m *CandidateTemp) String() string            { return proto.CompactTextString(m) }
func (*CandidateTemp) ProtoMessage()               {}
func (*CandidateTemp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CandidateTemp) GetPres() []*CandidateInfo {
	if m != nil {
		return m.Pres
	}
	return nil
}

func (m *CandidateTemp) GetCurrs() []*CandidateInfo {
	if m != nil {
		return m.Currs
	}
	return nil
}

func (m *CandidateTemp) GetNexts() []*CandidateInfo {
	if m != nil {
		return m.Nexts
	}
	return nil
}

func (m *CandidateTemp) GetImms() []*CandidateInfo {
	if m != nil {
		return m.Imms
	}
	return nil
}

func (m *CandidateTemp) GetRes() []*CandidateInfo {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *CandidateTemp) GetRefunds() map[string]*RefundArr {
	if m != nil {
		return m.Refunds
	}
	return nil
}

type TxHashArr struct {
	TxHashs [][]byte `protobuf:"bytes,1,rep,name=TxHashs,proto3" json:"TxHashs,omitempty"`
}

func (m *TxHashArr) Reset()                    { *m = TxHashArr{} }
func (m *TxHashArr) String() string            { return proto.CompactTextString(m) }
func (*TxHashArr) ProtoMessage()               {}
func (*TxHashArr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TxHashArr) GetTxHashs() [][]byte {
	if m != nil {
		return m.TxHashs
	}
	return nil
}

type Field struct {
	TxHash    []byte `protobuf:"bytes,1,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	Remaining uint32 `protobuf:"varint,2,opt,name=Remaining" json:"Remaining,omitempty"`
	Price     string `protobuf:"bytes,3,opt,name=Price" json:"Price,omitempty"`
}

func (m *Field) Reset()                    { *m = Field{} }
func (m *Field) String() string            { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()               {}
func (*Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Field) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *Field) GetRemaining() uint32 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *Field) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

type TicketDependency struct {
	//    uint64  Age = 1;
	Num uint32 `protobuf:"varint,2,opt,name=Num" json:"Num,omitempty"`
	//    repeated bytes  Tids = 3;
	Tinfo []*Field `protobuf:"bytes,3,rep,name=Tinfo" json:"Tinfo,omitempty"`
}

func (m *TicketDependency) Reset()                    { *m = TicketDependency{} }
func (m *TicketDependency) String() string            { return proto.CompactTextString(m) }
func (*TicketDependency) ProtoMessage()               {}
func (*TicketDependency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TicketDependency) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *TicketDependency) GetTinfo() []*Field {
	if m != nil {
		return m.Tinfo
	}
	return nil
}

type TicketTemp struct {
	Sq int32 `protobuf:"varint,1,opt,name=Sq" json:"Sq,omitempty"`
	//    map<string, TicketInfo> Infos = 2;
	//    map<string, TxHashArr> Ets  = 3;
	Dependencys map[string]*TicketDependency `protobuf:"bytes,4,rep,name=Dependencys" json:"Dependencys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TicketTemp) Reset()                    { *m = TicketTemp{} }
func (m *TicketTemp) String() string            { return proto.CompactTextString(m) }
func (*TicketTemp) ProtoMessage()               {}
func (*TicketTemp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TicketTemp) GetSq() int32 {
	if m != nil {
		return m.Sq
	}
	return 0
}

func (m *TicketTemp) GetDependencys() map[string]*TicketDependency {
	if m != nil {
		return m.Dependencys
	}
	return nil
}

type PB_PPosTemp struct {
	CanTmp      *CandidateTemp `protobuf:"bytes,1,opt,name=CanTmp" json:"CanTmp,omitempty"`
	TickTmp     *TicketTemp    `protobuf:"bytes,2,opt,name=TickTmp" json:"TickTmp,omitempty"`
	BlockNumber string         `protobuf:"bytes,3,opt,name=BlockNumber" json:"BlockNumber,omitempty"`
	BlockHash   string         `protobuf:"bytes,4,opt,name=BlockHash" json:"BlockHash,omitempty"`
}

func (m *PB_PPosTemp) Reset()                    { *m = PB_PPosTemp{} }
func (m *PB_PPosTemp) String() string            { return proto.CompactTextString(m) }
func (*PB_PPosTemp) ProtoMessage()               {}
func (*PB_PPosTemp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PB_PPosTemp) GetCanTmp() *CandidateTemp {
	if m != nil {
		return m.CanTmp
	}
	return nil
}

func (m *PB_PPosTemp) GetTickTmp() *TicketTemp {
	if m != nil {
		return m.TickTmp
	}
	return nil
}

func (m *PB_PPosTemp) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *PB_PPosTemp) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func init() {
	proto.RegisterType((*CandidateInfo)(nil), "ppos_storage.CandidateInfo")
	proto.RegisterType((*Refund)(nil), "ppos_storage.Refund")
	proto.RegisterType((*RefundArr)(nil), "ppos_storage.RefundArr")
	proto.RegisterType((*CandidateTemp)(nil), "ppos_storage.CandidateTemp")
	proto.RegisterType((*TxHashArr)(nil), "ppos_storage.TxHashArr")
	proto.RegisterType((*Field)(nil), "ppos_storage.Field")
	proto.RegisterType((*TicketDependency)(nil), "ppos_storage.TicketDependency")
	proto.RegisterType((*TicketTemp)(nil), "ppos_storage.TicketTemp")
	proto.RegisterType((*PB_PPosTemp)(nil), "ppos_storage.PB_PPosTemp")
}

func init() { proto.RegisterFile("ppos_storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x9a, 0x26, 0x25, 0x37, 0x1d, 0x9a, 0xcc, 0x04, 0xd6, 0x98, 0x50, 0x15, 0x09, 0xa9,
	0x7b, 0x58, 0x11, 0x1b, 0x0f, 0x08, 0x9e, 0xf6, 0xa9, 0x4d, 0x48, 0x5b, 0xe5, 0xe6, 0x89, 0x07,
	0xa6, 0xac, 0x71, 0x47, 0xb4, 0xc5, 0xc9, 0xec, 0x14, 0xba, 0x1f, 0x83, 0xf8, 0x17, 0xfc, 0x07,
	0xfe, 0x15, 0xf2, 0x75, 0x42, 0x92, 0xb1, 0x6a, 0x93, 0x78, 0xf3, 0xbd, 0x39, 0xe7, 0xf8, 0xda,
	0xe7, 0xc4, 0x40, 0xf2, 0x3c, 0x53, 0xe7, 0xaa, 0xc8, 0x64, 0x74, 0xc9, 0x47, 0xb9, 0xcc, 0x8a,
	0x8c, 0xf4, 0x9b, 0xbd, 0xe0, 0x47, 0x07, 0x56, 0xf6, 0x23, 0x11, 0x27, 0x71, 0x54, 0xf0, 0x13,
	0x31, 0xcb, 0x08, 0x85, 0xde, 0x01, 0xcf, 0x33, 0x95, 0x14, 0xd4, 0x1a, 0x58, 0x43, 0x8f, 0x55,
	0x25, 0x19, 0x80, 0xbf, 0x77, 0x9d, 0x4d, 0xaf, 0x4e, 0xe7, 0xe9, 0x05, 0x97, 0xb4, 0x83, 0x5f,
	0x9b, 0x2d, 0xcd, 0x0d, 0x17, 0x27, 0x22, 0xe6, 0x0b, 0x6a, 0x0f, 0xac, 0xe1, 0x0a, 0xab, 0x4a,
	0xcd, 0xad, 0xb7, 0x89, 0x69, 0x77, 0x60, 0x0d, 0xfb, 0xac, 0xd9, 0x22, 0x04, 0xba, 0xc7, 0x99,
	0x2a, 0xa8, 0x83, 0xb2, 0xb8, 0xd6, 0xbd, 0x71, 0x26, 0x0b, 0xea, 0x9a, 0x9e, 0x5e, 0x93, 0x35,
	0x70, 0xce, 0xbe, 0x0b, 0x2e, 0x69, 0x0f, 0x35, 0x4c, 0xa1, 0xbb, 0x87, 0x8b, 0x42, 0x46, 0xf4,
	0x09, 0x42, 0x4d, 0x41, 0x56, 0xc1, 0x3e, 0xe2, 0x9c, 0x7a, 0x38, 0x8b, 0x5e, 0x92, 0xe7, 0xe0,
	0x86, 0x8b, 0xe3, 0x48, 0x7d, 0xa5, 0x80, 0xf4, 0xb2, 0xc2, 0xbe, 0x91, 0xf5, 0xcb, 0x3e, 0x56,
	0xc1, 0x67, 0x70, 0x19, 0x9f, 0xcd, 0x45, 0xfc, 0x5f, 0xf7, 0xf2, 0x77, 0x66, 0xbb, 0x31, 0x73,
	0xf0, 0x11, 0x3c, 0xa3, 0xbd, 0x2b, 0x25, 0x19, 0x69, 0xf9, 0x19, 0x8f, 0x0a, 0x45, 0xad, 0x81,
	0x3d, 0xf4, 0xb7, 0xd7, 0x46, 0x2d, 0xf3, 0x0c, 0x92, 0x55, 0xa0, 0xe0, 0xa7, 0xdd, 0x30, 0x2e,
	0xe4, 0x69, 0x4e, 0xde, 0x40, 0x37, 0x97, 0xbc, 0xa2, 0xbf, 0x6c, 0xd3, 0x5b, 0x1e, 0x33, 0x04,
	0x92, 0xb7, 0xe0, 0x4c, 0xe7, 0x52, 0x2a, 0xda, 0x79, 0x98, 0x61, 0x90, 0x9a, 0x22, 0xf8, 0xa2,
	0x50, 0xd4, 0x7e, 0x04, 0x05, 0x91, 0x7a, 0xac, 0x24, 0x4d, 0x15, 0xed, 0x3e, 0x62, 0x2c, 0x0d,
	0x24, 0x5b, 0x60, 0xeb, 0x63, 0x38, 0x0f, 0xe3, 0x35, 0x8e, 0xec, 0x41, 0x4f, 0xe2, 0xdd, 0x28,
	0xea, 0x22, 0x65, 0xb8, 0x84, 0xa2, 0x2f, 0xa9, 0xbc, 0x46, 0x75, 0x28, 0x0a, 0x79, 0xcb, 0x2a,
	0xe2, 0xfa, 0x04, 0xfa, 0xcd, 0x0f, 0x3a, 0x37, 0x57, 0xfc, 0xb6, 0xf4, 0x59, 0x2f, 0xc9, 0x16,
	0x38, 0xdf, 0xa2, 0xeb, 0x39, 0x47, 0x77, 0xfd, 0xed, 0x17, 0xf7, 0x99, 0xb3, 0x2b, 0x25, 0x33,
	0xa8, 0x0f, 0x9d, 0xf7, 0x56, 0xf0, 0x1a, 0x3c, 0x13, 0x2e, 0x6d, 0x2f, 0xfe, 0x19, 0xba, 0x30,
	0xfe, 0xf4, 0x59, 0x55, 0x06, 0x13, 0x70, 0x8e, 0x12, 0x7e, 0x1d, 0x37, 0xa2, 0x69, 0xb5, 0xa2,
	0xb9, 0xa1, 0x63, 0x92, 0x46, 0x89, 0x48, 0xc4, 0x25, 0x6e, 0xbf, 0xc2, 0xea, 0x86, 0x8e, 0xd6,
	0x58, 0x26, 0x53, 0x8e, 0xd1, 0xf2, 0x98, 0x29, 0x82, 0x33, 0x58, 0x0d, 0x93, 0xe9, 0x15, 0x2f,
	0x0e, 0x78, 0xce, 0x45, 0xcc, 0xc5, 0x14, 0x0f, 0x75, 0x3a, 0x4f, 0x4b, 0x05, 0xbd, 0x24, 0x9b,
	0xe0, 0x84, 0x89, 0x98, 0x65, 0xa5, 0x9b, 0xcf, 0xda, 0x87, 0xc2, 0xa9, 0x98, 0x41, 0x04, 0xbf,
	0x2d, 0x00, 0xa3, 0x88, 0x59, 0x7b, 0x0a, 0x9d, 0xc9, 0x0d, 0xce, 0xe9, 0xb0, 0xce, 0xe4, 0x86,
	0x7c, 0x02, 0xbf, 0xde, 0xa9, 0xf2, 0x7a, 0xb3, 0xad, 0x57, 0xd3, 0x47, 0x0d, 0xac, 0x71, 0xa2,
	0xc9, 0x5e, 0xff, 0x02, 0xab, 0x77, 0x01, 0xf7, 0x38, 0xf2, 0xae, 0xed, 0xc8, 0xab, 0xfb, 0x36,
	0xab, 0x65, 0x9a, 0xc6, 0xfc, 0xb2, 0xc0, 0x1f, 0xef, 0x9d, 0x8f, 0xc7, 0x99, 0xc2, 0xc3, 0xec,
	0x80, 0xbb, 0x1f, 0x89, 0x30, 0xcd, 0x51, 0x7e, 0x79, 0xe6, 0x34, 0x98, 0x95, 0x50, 0xb2, 0x0d,
	0x3d, 0xbd, 0x87, 0x66, 0x99, 0x01, 0xe8, 0xb2, 0xd3, 0xb2, 0x0a, 0x78, 0xf7, 0xa1, 0xb0, 0xff,
	0x7d, 0x28, 0x36, 0xc0, 0xc3, 0x12, 0x63, 0xd0, 0xc5, 0xef, 0x75, 0xe3, 0xc2, 0xc5, 0x17, 0x7c,
	0xe7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x69, 0xa5, 0xfa, 0xd7, 0x05, 0x00, 0x00,
}
