// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ppos_storage.proto

/*
Package ppos_storage is a generated protocol buffer package.

It is generated from these files:
	ppos_storage.proto

It has these top-level messages:
	CandidateInfo
	Refund
	RefundArr
	CandidateTemp
	TicketInfo
	TxHashArr
	TicketDependency
	TicketTemp
	PB_PPosTemp
*/
package ppos_storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CandidateInfo struct {
	Deposit     string `protobuf:"bytes,1,opt,name=Deposit" json:"Deposit,omitempty"`
	BlockNumber string `protobuf:"bytes,2,opt,name=BlockNumber" json:"BlockNumber,omitempty"`
	TxIndex     uint32 `protobuf:"varint,3,opt,name=TxIndex" json:"TxIndex,omitempty"`
	CandidateId []byte `protobuf:"bytes,4,opt,name=CandidateId,proto3" json:"CandidateId,omitempty"`
	Host        string `protobuf:"bytes,5,opt,name=Host" json:"Host,omitempty"`
	Port        string `protobuf:"bytes,6,opt,name=Port" json:"Port,omitempty"`
	Owner       []byte `protobuf:"bytes,7,opt,name=Owner,proto3" json:"Owner,omitempty"`
	//  string    From          = 8;
	Extra  string `protobuf:"bytes,8,opt,name=Extra" json:"Extra,omitempty"`
	Fee    uint32 `protobuf:"varint,9,opt,name=Fee" json:"Fee,omitempty"`
	TxHash []byte `protobuf:"bytes,10,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	TOwner []byte `protobuf:"bytes,11,opt,name=TOwner,proto3" json:"TOwner,omitempty"`
}

func (m *CandidateInfo) Reset()                    { *m = CandidateInfo{} }
func (m *CandidateInfo) String() string            { return proto.CompactTextString(m) }
func (*CandidateInfo) ProtoMessage()               {}
func (*CandidateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CandidateInfo) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *CandidateInfo) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *CandidateInfo) GetTxIndex() uint32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *CandidateInfo) GetCandidateId() []byte {
	if m != nil {
		return m.CandidateId
	}
	return nil
}

func (m *CandidateInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CandidateInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CandidateInfo) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CandidateInfo) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *CandidateInfo) GetFee() uint32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *CandidateInfo) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *CandidateInfo) GetTOwner() []byte {
	if m != nil {
		return m.TOwner
	}
	return nil
}

type Refund struct {
	Deposit     string `protobuf:"bytes,1,opt,name=Deposit" json:"Deposit,omitempty"`
	BlockNumber string `protobuf:"bytes,2,opt,name=BlockNumber" json:"BlockNumber,omitempty"`
	Owner       []byte `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
}

func (m *Refund) Reset()                    { *m = Refund{} }
func (m *Refund) String() string            { return proto.CompactTextString(m) }
func (*Refund) ProtoMessage()               {}
func (*Refund) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Refund) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *Refund) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Refund) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

type RefundArr struct {
	Defeats []*Refund `protobuf:"bytes,1,rep,name=Defeats" json:"Defeats,omitempty"`
}

func (m *RefundArr) Reset()                    { *m = RefundArr{} }
func (m *RefundArr) String() string            { return proto.CompactTextString(m) }
func (*RefundArr) ProtoMessage()               {}
func (*RefundArr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RefundArr) GetDefeats() []*Refund {
	if m != nil {
		return m.Defeats
	}
	return nil
}

type CandidateTemp struct {
	//  three round witness
	Pres  []*CandidateInfo `protobuf:"bytes,1,rep,name=pres" json:"pres,omitempty"`
	Currs []*CandidateInfo `protobuf:"bytes,2,rep,name=currs" json:"currs,omitempty"`
	Nexts []*CandidateInfo `protobuf:"bytes,3,rep,name=nexts" json:"nexts,omitempty"`
	// can pool
	Imms []*CandidateInfo `protobuf:"bytes,4,rep,name=imms" json:"imms,omitempty"`
	Res  []*CandidateInfo `protobuf:"bytes,5,rep,name=res" json:"res,omitempty"`
	// refunds
	Refunds map[string]*RefundArr `protobuf:"bytes,6,rep,name=refunds" json:"refunds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CandidateTemp) Reset()                    { *m = CandidateTemp{} }
func (m *CandidateTemp) String() string            { return proto.CompactTextString(m) }
func (*CandidateTemp) ProtoMessage()               {}
func (*CandidateTemp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CandidateTemp) GetPres() []*CandidateInfo {
	if m != nil {
		return m.Pres
	}
	return nil
}

func (m *CandidateTemp) GetCurrs() []*CandidateInfo {
	if m != nil {
		return m.Currs
	}
	return nil
}

func (m *CandidateTemp) GetNexts() []*CandidateInfo {
	if m != nil {
		return m.Nexts
	}
	return nil
}

func (m *CandidateTemp) GetImms() []*CandidateInfo {
	if m != nil {
		return m.Imms
	}
	return nil
}

func (m *CandidateTemp) GetRes() []*CandidateInfo {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *CandidateTemp) GetRefunds() map[string]*RefundArr {
	if m != nil {
		return m.Refunds
	}
	return nil
}

type TicketInfo struct {
	Owner       []byte `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Deposit     string `protobuf:"bytes,2,opt,name=Deposit" json:"Deposit,omitempty"`
	CandidateId []byte `protobuf:"bytes,3,opt,name=CandidateId,proto3" json:"CandidateId,omitempty"`
	BlockNumber string `protobuf:"bytes,4,opt,name=BlockNumber" json:"BlockNumber,omitempty"`
	Remaining   uint32 `protobuf:"varint,5,opt,name=Remaining" json:"Remaining,omitempty"`
}

func (m *TicketInfo) Reset()                    { *m = TicketInfo{} }
func (m *TicketInfo) String() string            { return proto.CompactTextString(m) }
func (*TicketInfo) ProtoMessage()               {}
func (*TicketInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TicketInfo) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *TicketInfo) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

func (m *TicketInfo) GetCandidateId() []byte {
	if m != nil {
		return m.CandidateId
	}
	return nil
}

func (m *TicketInfo) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *TicketInfo) GetRemaining() uint32 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

type TxHashArr struct {
	TxHashs [][]byte `protobuf:"bytes,1,rep,name=TxHashs,proto3" json:"TxHashs,omitempty"`
}

func (m *TxHashArr) Reset()                    { *m = TxHashArr{} }
func (m *TxHashArr) String() string            { return proto.CompactTextString(m) }
func (*TxHashArr) ProtoMessage()               {}
func (*TxHashArr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TxHashArr) GetTxHashs() [][]byte {
	if m != nil {
		return m.TxHashs
	}
	return nil
}

type TicketDependency struct {
	Age  uint64   `protobuf:"varint,1,opt,name=Age" json:"Age,omitempty"`
	Num  uint32   `protobuf:"varint,2,opt,name=Num" json:"Num,omitempty"`
	Tids [][]byte `protobuf:"bytes,3,rep,name=Tids,proto3" json:"Tids,omitempty"`
}

func (m *TicketDependency) Reset()                    { *m = TicketDependency{} }
func (m *TicketDependency) String() string            { return proto.CompactTextString(m) }
func (*TicketDependency) ProtoMessage()               {}
func (*TicketDependency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TicketDependency) GetAge() uint64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *TicketDependency) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *TicketDependency) GetTids() [][]byte {
	if m != nil {
		return m.Tids
	}
	return nil
}

type TicketTemp struct {
	Sq          int32                        `protobuf:"varint,1,opt,name=Sq" json:"Sq,omitempty"`
	Infos       map[string]*TicketInfo       `protobuf:"bytes,2,rep,name=Infos" json:"Infos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ets         map[string]*TxHashArr        `protobuf:"bytes,3,rep,name=Ets" json:"Ets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dependencys map[string]*TicketDependency `protobuf:"bytes,4,rep,name=Dependencys" json:"Dependencys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TicketTemp) Reset()                    { *m = TicketTemp{} }
func (m *TicketTemp) String() string            { return proto.CompactTextString(m) }
func (*TicketTemp) ProtoMessage()               {}
func (*TicketTemp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TicketTemp) GetSq() int32 {
	if m != nil {
		return m.Sq
	}
	return 0
}

func (m *TicketTemp) GetInfos() map[string]*TicketInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *TicketTemp) GetEts() map[string]*TxHashArr {
	if m != nil {
		return m.Ets
	}
	return nil
}

func (m *TicketTemp) GetDependencys() map[string]*TicketDependency {
	if m != nil {
		return m.Dependencys
	}
	return nil
}

type PB_PPosTemp struct {
	CanTmp      *CandidateTemp `protobuf:"bytes,1,opt,name=CanTmp" json:"CanTmp,omitempty"`
	TickTmp     *TicketTemp    `protobuf:"bytes,2,opt,name=TickTmp" json:"TickTmp,omitempty"`
	BlockNumber string         `protobuf:"bytes,3,opt,name=BlockNumber" json:"BlockNumber,omitempty"`
	BlockHash   string         `protobuf:"bytes,4,opt,name=BlockHash" json:"BlockHash,omitempty"`
}

func (m *PB_PPosTemp) Reset()                    { *m = PB_PPosTemp{} }
func (m *PB_PPosTemp) String() string            { return proto.CompactTextString(m) }
func (*PB_PPosTemp) ProtoMessage()               {}
func (*PB_PPosTemp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PB_PPosTemp) GetCanTmp() *CandidateTemp {
	if m != nil {
		return m.CanTmp
	}
	return nil
}

func (m *PB_PPosTemp) GetTickTmp() *TicketTemp {
	if m != nil {
		return m.TickTmp
	}
	return nil
}

func (m *PB_PPosTemp) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *PB_PPosTemp) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func init() {
	proto.RegisterType((*CandidateInfo)(nil), "ppos_storage.CandidateInfo")
	proto.RegisterType((*Refund)(nil), "ppos_storage.Refund")
	proto.RegisterType((*RefundArr)(nil), "ppos_storage.RefundArr")
	proto.RegisterType((*CandidateTemp)(nil), "ppos_storage.CandidateTemp")
	proto.RegisterType((*TicketInfo)(nil), "ppos_storage.TicketInfo")
	proto.RegisterType((*TxHashArr)(nil), "ppos_storage.TxHashArr")
	proto.RegisterType((*TicketDependency)(nil), "ppos_storage.TicketDependency")
	proto.RegisterType((*TicketTemp)(nil), "ppos_storage.TicketTemp")
	proto.RegisterType((*PB_PPosTemp)(nil), "ppos_storage.PB_PPosTemp")
}

func init() { proto.RegisterFile("ppos_storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x38, 0x69, 0x26, 0x09, 0xaa, 0x56, 0x15, 0xac, 0x0a, 0x42, 0xc1, 0x08, 0x29,
	0x3c, 0x34, 0x88, 0x96, 0x07, 0x2e, 0x4f, 0xbd, 0x04, 0xb5, 0x20, 0xb5, 0xd1, 0x36, 0x4f, 0x3c,
	0x50, 0xb9, 0xf1, 0xb6, 0x58, 0xad, 0x2f, 0x5d, 0x3b, 0x90, 0x7e, 0x0c, 0xf0, 0x17, 0x7c, 0x0e,
	0xdf, 0x82, 0x66, 0x36, 0x8e, 0x37, 0x4d, 0x42, 0x8b, 0x78, 0x9b, 0x19, 0x9f, 0x33, 0x3b, 0x97,
	0x33, 0x09, 0xb0, 0x34, 0x4d, 0xb2, 0x93, 0x2c, 0x4f, 0x94, 0x7f, 0x2e, 0xbb, 0xa9, 0x4a, 0xf2,
	0x84, 0x35, 0xcd, 0x98, 0xf7, 0xdd, 0x86, 0xd6, 0xae, 0x1f, 0x07, 0x61, 0xe0, 0xe7, 0xf2, 0x20,
	0x3e, 0x4b, 0x18, 0x87, 0xda, 0x9e, 0x4c, 0x93, 0x2c, 0xcc, 0xb9, 0xd5, 0xb6, 0x3a, 0x75, 0x51,
	0xb8, 0xac, 0x0d, 0x8d, 0x9d, 0xcb, 0x64, 0x78, 0x71, 0x38, 0x8a, 0x4e, 0xa5, 0xe2, 0x36, 0x7d,
	0x35, 0x43, 0xc8, 0x1d, 0x8c, 0x0f, 0xe2, 0x40, 0x8e, 0xb9, 0xd3, 0xb6, 0x3a, 0x2d, 0x51, 0xb8,
	0xc8, 0x2d, 0x9f, 0x09, 0x78, 0xa5, 0x6d, 0x75, 0x9a, 0xc2, 0x0c, 0x31, 0x06, 0x95, 0xfd, 0x24,
	0xcb, 0xb9, 0x4b, 0x69, 0xc9, 0xc6, 0x58, 0x3f, 0x51, 0x39, 0xaf, 0xea, 0x18, 0xda, 0x6c, 0x0d,
	0xdc, 0xa3, 0x6f, 0xb1, 0x54, 0xbc, 0x46, 0x39, 0xb4, 0x83, 0xd1, 0xde, 0x38, 0x57, 0x3e, 0x5f,
	0x21, 0xa8, 0x76, 0xd8, 0x2a, 0x38, 0xef, 0xa5, 0xe4, 0x75, 0xaa, 0x05, 0x4d, 0x76, 0x1f, 0xaa,
	0x83, 0xf1, 0xbe, 0x9f, 0x7d, 0xe1, 0x40, 0xf4, 0x89, 0x47, 0x71, 0x9d, 0xb6, 0x31, 0x89, 0x93,
	0xe7, 0x7d, 0x82, 0xaa, 0x90, 0x67, 0xa3, 0x38, 0xf8, 0xaf, 0xb9, 0x4c, 0x6b, 0x76, 0x8c, 0x9a,
	0xbd, 0x77, 0x50, 0xd7, 0xb9, 0xb7, 0x95, 0x62, 0x5d, 0x4c, 0x7f, 0x26, 0xfd, 0x3c, 0xe3, 0x56,
	0xdb, 0xe9, 0x34, 0x36, 0xd7, 0xba, 0x33, 0xcb, 0xd3, 0x48, 0x51, 0x80, 0xbc, 0x9f, 0x8e, 0xb1,
	0xb8, 0x81, 0x8c, 0x52, 0xf6, 0x02, 0x2a, 0xa9, 0x92, 0x05, 0xfd, 0xe1, 0x2c, 0x7d, 0x66, 0xc7,
	0x82, 0x80, 0xec, 0x25, 0xb8, 0xc3, 0x91, 0x52, 0x19, 0xb7, 0x6f, 0x67, 0x68, 0x24, 0x52, 0x62,
	0x39, 0xce, 0x33, 0xee, 0xdc, 0x81, 0x42, 0x48, 0x2c, 0x2b, 0x8c, 0xa2, 0x8c, 0x57, 0xee, 0x50,
	0x16, 0x02, 0xd9, 0x06, 0x38, 0xd8, 0x86, 0x7b, 0x3b, 0x1e, 0x71, 0x6c, 0x07, 0x6a, 0x8a, 0x66,
	0x93, 0xf1, 0x2a, 0x51, 0x3a, 0x4b, 0x28, 0x38, 0xa4, 0xc9, 0x18, 0xb3, 0x5e, 0x9c, 0xab, 0x6b,
	0x51, 0x10, 0xd7, 0x8f, 0xa1, 0x69, 0x7e, 0x40, 0xdd, 0x5c, 0xc8, 0xeb, 0xc9, 0x9e, 0xd1, 0x64,
	0x1b, 0xe0, 0x7e, 0xf5, 0x2f, 0x47, 0x92, 0xb6, 0xdb, 0xd8, 0x7c, 0xb0, 0x68, 0x39, 0xdb, 0x4a,
	0x09, 0x8d, 0x7a, 0x6b, 0xbf, 0xb6, 0xbc, 0x1f, 0x16, 0xc0, 0x20, 0x1c, 0x5e, 0xc8, 0x9c, 0xee,
	0x6a, 0xaa, 0x01, 0xcb, 0xd4, 0xad, 0xa1, 0x2a, 0x7b, 0x4e, 0x55, 0xe6, 0xc5, 0x38, 0xf3, 0x17,
	0x73, 0x43, 0x77, 0x95, 0x79, 0xdd, 0x3d, 0x42, 0x85, 0x45, 0x7e, 0x18, 0x87, 0xf1, 0x39, 0x1d,
	0x56, 0x4b, 0x94, 0x01, 0xef, 0x19, 0xd4, 0xb5, 0xfa, 0x51, 0x7f, 0x74, 0xba, 0xe8, 0x68, 0x01,
	0x35, 0x45, 0xe1, 0x7a, 0x1f, 0x60, 0x55, 0xb7, 0xb1, 0x27, 0x53, 0x19, 0x07, 0x32, 0x1e, 0xd2,
	0x80, 0xb6, 0xcf, 0x25, 0xb5, 0x52, 0x11, 0x68, 0x62, 0xe4, 0x70, 0x14, 0x51, 0x13, 0x2d, 0x81,
	0x26, 0x1e, 0xef, 0x20, 0x0c, 0xb4, 0x54, 0x9a, 0x82, 0x6c, 0xef, 0xb7, 0x53, 0xcc, 0x84, 0x24,
	0x7b, 0x0f, 0xec, 0xe3, 0x2b, 0xca, 0xe2, 0x0a, 0xfb, 0xf8, 0x8a, 0xbd, 0x01, 0x17, 0x67, 0x55,
	0x28, 0xf2, 0xe9, 0xec, 0x94, 0x4b, 0x62, 0x97, 0x50, 0x7a, 0x89, 0x9a, 0xc1, 0xb6, 0xc0, 0xe9,
	0x4d, 0x75, 0xf9, 0x64, 0x29, 0xb1, 0x97, 0x4f, 0x68, 0x88, 0x66, 0x1f, 0xa1, 0x51, 0x36, 0x55,
	0x48, 0xf4, 0xf9, 0x52, 0xb2, 0x81, 0xd5, 0x49, 0x4c, 0xf6, 0xba, 0x00, 0x28, 0xcb, 0x5a, 0x20,
	0xa1, 0xee, 0xac, 0x84, 0xf8, 0xa2, 0x67, 0xf4, 0xe1, 0x4c, 0x35, 0xb4, 0x7e, 0x04, 0x2b, 0x45,
	0xc5, 0xff, 0x2c, 0xca, 0xe9, 0x6e, 0xcd, 0x84, 0x9f, 0x61, 0xf5, 0x66, 0x17, 0x0b, 0x12, 0xbf,
	0x9a, 0x4d, 0xfc, 0x78, 0x51, 0xa9, 0x65, 0x1a, 0x53, 0xf4, 0xbf, 0x2c, 0x68, 0xf4, 0x77, 0x4e,
	0xfa, 0xfd, 0x24, 0xa3, 0x0d, 0x6f, 0x41, 0x75, 0xd7, 0x8f, 0x07, 0x51, 0x4a, 0xe9, 0x97, 0xdf,
	0x33, 0x82, 0xc5, 0x04, 0xca, 0x36, 0xa1, 0x86, 0x6f, 0x20, 0xeb, 0x2f, 0xb3, 0x22, 0x4a, 0x01,
	0xbc, 0x79, 0x0c, 0xce, 0xc2, 0x63, 0x20, 0x97, 0x7e, 0xfd, 0xf5, 0xb1, 0x94, 0x81, 0xd3, 0x2a,
	0xfd, 0x3b, 0x6e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xe6, 0x32, 0x90, 0x33, 0x07, 0x00,
	0x00,
}
