pragma solidity ^0.4.12;
/**
* @file LibFinancierInfo.sol
* @author yiyating
* @time 2016-12-27
* @desc 融资方信息定义
*/


import "../utillib/LibInt.sol";
import "../utillib/LibString.sol";
import "../utillib/LibJson.sol";
import "../utillib/LibStack.sol";

library LibFinancierInfo {
    using LibInt for *;
    using LibString for *;
    using LibJson for *;
    using LibFinancierInfo for *;

    // enum BoolEnum { NONE, T, F }
    
    /**
    * @dev Contruction
    */
    struct FinancierInfo {
        uint id;                //id
        string businessNo;        //业务流水号
        string userName;          //用户姓名
        address userId;         //发布者id
        uint8 userType;          //用户类型 1-个人，2-机构
        string secAccount;       //证券账户
        string secCode;         //证券代码
        string secName;         //证券简称
        uint hideFlag;          //是否隐藏出质数量
        uint pledgeNum;         //出质数量
        uint closePrice;        //近期收盘价
        uint industry;          //行业
        uint minAmountScale;      //最小资金规模
        uint maxAmountScale;      //最大资金规模
        uint minAmountLastDate;   //最小资金期限
        uint maxAmountLastDate;   //最大资金期限
        uint purpose;             //融资用途
        uint createTimestamp;     //创建时间
        uint endTimestamp;        //关闭时间
        uint status;              //状态
    }

    /**
    *@desc fromJson for FinancierInfo
    *      Generated by juzhen SolidityStructTool automatically.
    *      Not to edit this code manually.
    */
    function fromJson(FinancierInfo storage _self, string _json) internal returns(bool succ) {
        _self.reset();
        if(LibJson.push(_json) == 0) {
            return false;
        }

        if (!_json.isJson()) {
            LibJson.pop();
            return false;
        }

        _self.id = _json.jsonRead("id").toUint();
        _self.businessNo = _json.jsonRead("businessNo");
        _self.userName = _json.jsonRead("userName");
        _self.userId = _json.jsonRead("userId").toAddress();
        _self.userType = uint8(_json.jsonRead("userType").toUint());
        _self.secAccount = _json.jsonRead("secAccount");
        _self.secCode = _json.jsonRead("secCode");
        _self.secName = _json.jsonRead("secName");
        _self.hideFlag = _json.jsonRead("hideFlag").toUint();
        _self.pledgeNum = _json.jsonRead("pledgeNum").toUint();
        _self.closePrice = _json.jsonRead("closePrice").toUint();
        _self.industry = _json.jsonRead("industry").toUint();
        _self.minAmountScale = _json.jsonRead("minAmountScale").toUint();
        _self.maxAmountScale = _json.jsonRead("maxAmountScale").toUint();
        _self.minAmountLastDate = _json.jsonRead("minAmountLastDate").toUint();
        _self.maxAmountLastDate = _json.jsonRead("maxAmountLastDate").toUint();
        _self.purpose = _json.jsonRead("purpose").toUint();
        _self.createTimestamp = _json.jsonRead("createTimestamp").toUint();
        _self.endTimestamp = _json.jsonRead("endTimestamp").toUint();
        _self.status = _json.jsonRead("status").toUint();

        LibJson.pop();
        return true;
    }

    /**
    *@desc toJson for FinancierInfo
    *      Generated by juzhen SolidityStructTool automatically.
    *      Not to edit this code manually.
    */
    function toJson(FinancierInfo storage _self) internal constant returns (string _json) {
        uint len = 0;
        len = LibStack.push("{");
        len = LibStack.appendKeyValue("id", _self.id);
        len = LibStack.appendKeyValue("businessNo", _self.businessNo);
        len = LibStack.appendKeyValue("userName", _self.userName);
        len = LibStack.appendKeyValue("userId", _self.userId);
        len = LibStack.appendKeyValue("userType", uint(_self.userType));
        len = LibStack.appendKeyValue("secAccount", _self.secAccount);
        len = LibStack.appendKeyValue("secCode", _self.secCode);
        len = LibStack.appendKeyValue("secName", _self.secName);
        len = LibStack.appendKeyValue("hideFlag", _self.hideFlag);
        len = LibStack.appendKeyValue("pledgeNum", _self.pledgeNum);
        len = LibStack.appendKeyValue("closePrice", _self.closePrice);
        len = LibStack.appendKeyValue("industry", _self.industry);
        len = LibStack.appendKeyValue("minAmountScale", _self.minAmountScale);
        len = LibStack.appendKeyValue("maxAmountScale", _self.maxAmountScale);
        len = LibStack.appendKeyValue("minAmountLastDate", _self.minAmountLastDate);
        len = LibStack.appendKeyValue("maxAmountLastDate", _self.maxAmountLastDate);
        len = LibStack.appendKeyValue("purpose", _self.purpose);
        len = LibStack.appendKeyValue("createTimestamp", _self.createTimestamp);
        len = LibStack.appendKeyValue("endTimestamp", _self.endTimestamp);
        len = LibStack.appendKeyValue("status", _self.status);
        len = LibStack.append("}");
        _json = LibStack.popex(len);
    }

    /**
    *@desc update for FinancierInfo
    *      Generated by juzhen SolidityStructTool automatically.
    *      Not to edit this code manually.
    */
    function update(FinancierInfo storage _self, string _json) internal returns(bool succ) {
        if(LibJson.push(_json) == 0) {
            return false;
        }

        if (!_json.isJson()) {
            LibJson.pop();
            return false;
        }

        if (_json.jsonKeyExists("id"))
            _self.id = _json.jsonRead("id").toUint();
        if (_json.jsonKeyExists("businessNo"))
            _self.businessNo = _json.jsonRead("businessNo");
        if (_json.jsonKeyExists("userName"))
            _self.userName = _json.jsonRead("userName");
        if (_json.jsonKeyExists("userId"))
            _self.userId = _json.jsonRead("userId").toAddress();
        if (_json.jsonKeyExists("userType"))
            _self.userType = uint8(_json.jsonRead("userType").toUint());
        if (_json.jsonKeyExists("secAccount"))
            _self.secAccount = _json.jsonRead("secAccount");
        if (_json.jsonKeyExists("secCode"))
            _self.secCode = _json.jsonRead("secCode");
        if (_json.jsonKeyExists("secName"))
            _self.secName = _json.jsonRead("secName");
        if (_json.jsonKeyExists("hideFlag"))
            _self.hideFlag = _json.jsonRead("hideFlag").toUint();
        if (_json.jsonKeyExists("pledgeNum"))
            _self.pledgeNum = _json.jsonRead("pledgeNum").toUint();
        if (_json.jsonKeyExists("closePrice"))
            _self.closePrice = _json.jsonRead("closePrice").toUint();
        if (_json.jsonKeyExists("industry"))
            _self.industry = _json.jsonRead("industry").toUint();
        if (_json.jsonKeyExists("minAmountScale"))
            _self.minAmountScale = _json.jsonRead("minAmountScale").toUint();
        if (_json.jsonKeyExists("maxAmountScale"))
            _self.maxAmountScale = _json.jsonRead("maxAmountScale").toUint();
        if (_json.jsonKeyExists("minAmountLastDate"))
            _self.minAmountLastDate = _json.jsonRead("minAmountLastDate").toUint();
        if (_json.jsonKeyExists("maxAmountLastDate"))
            _self.maxAmountLastDate = _json.jsonRead("maxAmountLastDate").toUint();
        if (_json.jsonKeyExists("purpose"))
            _self.purpose = _json.jsonRead("purpose").toUint();
        if (_json.jsonKeyExists("createTimestamp"))
            _self.createTimestamp = _json.jsonRead("createTimestamp").toUint();
        if (_json.jsonKeyExists("endTimestamp"))
            _self.endTimestamp = _json.jsonRead("endTimestamp").toUint();
        if (_json.jsonKeyExists("status"))
            _self.status = _json.jsonRead("status").toUint();
        
        LibJson.pop();
        return true;
    }

    /**
    *@desc reset for FinancierInfo
    *      Generated by juzhen SolidityStructTool automatically.
    *      Not to edit this code manually.
    */
    function reset(FinancierInfo storage _self) internal {
        delete _self.id;
        delete _self.businessNo;
        delete _self.userName;
        delete _self.userId;
        delete _self.userType;
        delete _self.secAccount;
        delete _self.secCode;
        delete _self.secName;
        delete _self.hideFlag;
        delete _self.pledgeNum;
        delete _self.closePrice;
        delete _self.industry;
        delete _self.minAmountScale;
        delete _self.maxAmountScale;
        delete _self.minAmountLastDate;
        delete _self.maxAmountLastDate;
        delete _self.purpose;
        delete _self.createTimestamp;
        delete _self.endTimestamp;
        delete _self.status;
    }
}