name: golangci-lint
on:
  pull_request:
    branches: '**'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go

      - uses: actions/checkout@v3

      - name: make
        run: bash ./build/build_deps.sh

      - name: Get dependencies
        run : |
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
          skip-pkg-cache: true
