name: golangci-lint
on:
  pull_request:
    branches: '**'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16
        id: go

      - uses: actions/checkout@v3

      - name: make
        run: bash ./build/build_deps.sh

      - name: Get dependencies
        run : |
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'
          args: --no-config  --issues-exit-code=0 --timeout=30m --tests=false --skip-dirs="tests" --skip-dirs-use-default=true --disable-all   --enable=misspell --enable=goconst --enable=gofmt --enable=goimports  --enable=gosec  --enable=unconvert  --enable=unparam  --enable=funlen
          skip-go-installation: true
          skip-pkg-cache: true
